### 1.CONFIG: PORT, CONTEXT PATH ###
#server.servlet.context-path: /zuul+
server:
   port: 8088
   error:
      include-message: always
#   servlet:
#      context-path: /new-root #thay đổi áấu hình root ứng dụng
   enable-swagger: true
   req-param-auth-tag: api_key, access_token
   route:
      jwt:
         secret: 7xC01tFjh1&IoUcb #jwt chuoi bi mat

spring:
   jndi:
      ignore: true #fix loi bao mat log4j

###2.DB CONFIG ###
datasources:
   dbKttTest:
      dbKey: dbKttTest
      dbType: oracle
      dbName: E_DVC
      driverClassName: oracle.jdbc.OracleDriver
      jdbcUrl: jdbc:oracle:thin:@10.0.227.31:1521:oradb01
      username: E_DVC
      password: Oracle123
      maximumPoolSize: 10
      minimumIdle: 10
      poolName: db_oracle_e_ktt_dev
      createPool: true
   dbKttDev:
      dbKey: dbKttDev
      dbType: oracle
      dbName: E_DVC
      driverClassName: oracle.jdbc.OracleDriver
      jdbcUrl: jdbc:oracle:thin:@10.0.227.31:1521:oradb01
      username: E_DVC
      password: Oracle123
      maximumPoolSize: 10
      minimumIdle: 10
      poolName: db_oracle_e_ktt_test
      createPool: true
   dbttsh:
      dbKey: dbttsh
      dbType: postgres
      dbName: mot_ttsh_dev
      driverClassName: org.postgresql.Driver
      jdbcUrl: jdbc:postgresql://10.0.227.30:5432/mot_ttsh_dev?prepareThreshold=0
      username: ttsh_dev
      password: TTSH#123456
      maximumPoolSize: 10
      minimumIdle: 10
      poolName: db_postgres_ttsh_dev
      createPool: true
   gplxTtsh:
      dbKey: gplxTtsh
      dbType: mssql
      dbName: GPLX_TTSH
      driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
      jdbcUrl: jdbc:sqlserver://10.0.223.154:1433;databaseName=GPLX_TTSH;instanceName=MSSQLSERVER;encrypt=true;trustServerCertificate=true;
      username: sa
      password: 123456a@
      maximumPoolSize: 10
      minimumIdle: 10
      poolName: db_sqlserver_gplx_ttsh
      createPool: true

##3. Auth:
jwt:
   key: 9a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c8b5f6v8a3d9
   access-token-expiration: 3600000
   refresh-token-expiration: 86400000